// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "email": "versilistyson@gmail.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/channels/message": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Send new message to channel",
                "parameters": [
                    {
                        "description": "Input for new message",
                        "name": "newMessageInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.NewMessageInput"
                        }
                    }
                ]
            }
        },
        "/channels/messages/newest": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "channels"
                ],
                "summary": "Get newest message from channel",
                "parameters": [
                    {
                        "description": "Channel messages input",
                        "name": "channelMessagesInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.AllChannelMessagesInput"
                        }
                    }
                ]
            }
        },
        "/channels/new": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "channels"
                ],
                "summary": "Create a group channel",
                "parameters": [
                    {
                        "description": "Input for new group channel",
                        "name": "newGroupChannelInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.NewGroupChannelInput"
                        }
                    }
                ]
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration info",
                        "name": "userRegistrationInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UserRegInput"
                        }
                    }
                ]
            }
        }
    },
    "definitions": {
        "main.AllChannelMessagesInput": {
            "type": "object",
            "properties": {
                "channelName": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "main.NewGroupChannelInput": {
            "type": "object",
            "properties": {
                "accessType": {
                    "type": "string"
                },
                "channelName": {
                    "type": "string"
                },
                "ownerUsername": {
                    "type": "string"
                }
            }
        },
        "main.NewMessageInput": {
            "type": "object",
            "properties": {
                "channelName": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "senderUsername": {
                    "type": "string"
                }
            }
        },
        "main.UserRegInput": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "isUserAdmin": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "https://mthree-go-irc.herokuapp.com",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Go-IRC API",
	Description: "This is a server created by Matt,Prithvi, and Versilis for the final mthree assessment",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
